[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Optional: increase timeout and memory if needed for SMTP and file downloads
#[[functions.included_files]]
#  path = "netlify/functions/**"

# Uncomment to set a longer timeout for specific functions
#[[functions]]
#  name = "send-application-email"
#  timeout = 26

[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 5173
  functions = "netlify/functions"